### PR TITLE
update version of ckantoolkit to mirror req from ckanext-harvest

### PR DESCRIPTION
**Pull request by btylerburton**
gitignore src dir

### CODE REVIEW

**Comment by btylerburton** [comment]
Fixes https://github.com/gsa/data.gov/issues/3851

**Comment by robert-bryson** [comment]
We intentionally don't care about 2.8 stuff on this anymore, right?

**Review by nickumia-reisys — CHANGES_REQUESTED** [review]
- `boto` is referenced [here](https://github.com/GSA/ckanext-geodatagov/blob/main/setup.py#L33), so it can be taken out of `requirements.txt`
- `future` is referenced in the datagovtheme extension, if it is also a requirement for this extension, we can move it to the `setup.py`
- `jsonschema` is also a [datajson ](https://github.com/GSA/ckanext-datajson/blob/main/setup.py#L32)requirement, so it can be taken out of `requirements.txt`
- `pyyaml` is also a [datajson ](https://github.com/GSA/ckanext-datajson/blob/main/setup.py#L31)requirement, so it can be taken out of `requirements.txt`

I'm explicitly ignoring changes to `requirement-py2.txt` since we're getting rid of it very very soon.

**Comment by btylerburton** [comment]
Perfect. 

Will clean this up to remove the datajson reqs.

Let's chat at standup if we want to remove `2.8` from the matrix build workflows. I believe we do.

**Comment by btylerburton** [comment]
I see `jsonschema` and `pyaml` are only referenced in `requirements-py2.txt`. Does this mean we can rip them out entirely?

**Review by nickumia-reisys — APPROVED** [review]
🥛

**Pull request merged**
