### PR TITLE
Db solr sync

### PR DESCRIPTION
**Pull request by Jin-Sun-tts**
Related to 
- https://github.com/GSA/data.gov/issues/2213

Changes:
- Add new db-solr-sync command without using temp table in DB
- Remove old db_solr_sync function from commands.py
- Remove the temp table miscs_solr_sync related codes.

### CODE REVIEW

**Comment by robert-bryson** [comment]
@Jin-Sun-tts, it does look like tests pass, but there are an [awful lot of exceptions](https://github.com/GSA/ckanext-geodatagov/actions/runs/3137916610/jobs/5096650668#step:3:629) happening in the logs. Is that expected? Which tests are testing this specifically?

**Comment by nickumia-reisys** [comment]
Example of how to manually run command locally:
```bash
CKAN_VERSION=2.9 docker-compose run app /bin/bash -c "ckan -c /srv/app/test.ini geodatagov db-solr-sync"
```

**Comment by nickumia-reisys** [comment]
Explanation example of db_solr_sync algorithm:
```
db = [(1,a),(2,b),(3,c)]
solr = [(2,b),(3,f),(4,g)]

db_not_in_solr = [(1,a),(3,c)]
solr_not_in_db = [(3,f),(4,g)]

work_to_do = {
   1: db
   3: db, solr
   4: solr
}
```

**Review by nickumia-reisys — APPROVED** [review]
🐧

**Pull request merged**
